apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  completions: 1
  template:
    metadata:
      name: db-migrate
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrate
        image: gcr.io/rails-lab-260819/appbasico:latest
        args:  ["bundle", "exec", "rake", "db:create", "db:migrate"]
        envFrom:
        - secretRef:
            name: file-secret


